- components/FooterPrimary.vue
> Update FooterPrimary styles

- components/FooterPrimary.vue
- components/FooterSock.vue
- layouts/default.vue
- pages/about/staff/_slug.vue
- pages/help/services-resources/_slug.vue
- plugins/craft.js
Added console.log to debug the live preview issue with footerprimary data or ask a librarian data and vuex state.
> Debug statements to find the Live Preview issue

- components/BlockCallToActionTwoUp.vue
- components/Flexible/MediaWithText.vue
- components/FooterPrimary.vue
- components/FooterSock.vue
- components/SimpleCards.vue
- layouts/default.vue
- pages/about/staff/_slug.vue
- pages/help/services-resources/_slug.vue
- plugins/craft.js
- stories/FooterPrimary.stories.js
- stories/FooterSock.stories.js
Move vuex footer data to components and add vuex to stories.
Always check for duplicate keys in v-for
vuex did not work in computed of page component for askalibrarian, so moved it to asyncdata
> Apps 1521 vuex stories

- components/BlockStaffDetail.vue
- components/Flexible/MediaWithText.vue
- stories/Flexible_MediaWithText.stories.js
Connected to [APPS-1547](https://jira.library.ucla.edu/browse/APPS-1547) and [APPS-1548](https://jira.library.ucla.edu/browse/APPS-1548)
Change "Ask me About" in BlockStaffDetail to "Ask Me About"
Add title from media with text component to front-end display
> APPS-1547 and APPS-1548 BlockStaffDetail and MediaWithText Bugs

- components/BlockCallToAction.vue
- pages/help/services-resources/_slug.vue
- stories/BlockCallToAction.stories.js
Connected to [APPS-1535](https://jira.library.ucla.edu/browse/APPS-1535)
Acceptance Criteria:
Component has a new prop isGlobal either true or false
vuex store use to fetch Global data if isGlobal is true
> APPS-1535 Restructure AskaLibrarian component to use store

- components/BlockHours.vue
- static/blockHours.html
thank @dianneweinthal for finding the solution. 
https://locastic.com/blog/dynamic-adjustment-of-the-iframe-height/
This PR enables the iframe to resize by sending messages from the iframe to its parent and updating the height of the iframe dynamically.
> fix[component]:Add resize iframe using window post message

- components/BlockMediaWithText.vue
- components/ButtonLink.vue
- components/Flexible/MediaWithText.vue
- components/FlexibleBlocks.vue
- components/SmartLink.vue
- gql/queries/LocationDetail.gql
- gql/queries/ServiceOrResourceDetail.gql
- stories/BlockMediaWithText.stories.js
- stories/Flexible_MediaWithText.spec.js
- stories/Flexible_MediaWithText.stories.js
Connected to [APPS-1522](https://jira.library.ucla.edu/browse/APPS-1522)
Fix MediaWithText to match Craft structure
> APPS-1522 FIX Flexible/MediaWithText Component

- components/SearchGenericFilterButtons.vue
- components/SearchGenericViewModes.vue
Connected to [APPS-1559](https://jira.library.ucla.edu/browse/APPS-1559)
> style: update styles to current variables

- components/FlexibleBlocks.vue
- gql/queries/ServiceOrResourceDetail.gql
Updates GraphQL query and adds MediaGallery to FlexibleBlocks component.
> Integrate MediaGallery into services item page

- components/HeaderMain.vue
- components/HeaderMainResponsive.vue
- components/HeaderSmart.vue
- cypress/integration/homepage.spec.js
- cypress/integration/mobilehomepage.spec.js
- layouts/default.vue
- stories/HeaderMainResponsive.stories.js
- stories/HeaderSmart.spec.js
- stories/HeaderSmart.stories.js
Connected to [APPS-1561](https://jira.library.ucla.edu/browse/APPS-1561)
> feat: Add HeaderMainResponsive to layout

- components/BannerHeader.vue
- components/BlockMediaWithText.vue
- components/BlockSimpleCard.vue
- components/Flexible/MediaWithText.vue
- components/Flexible/SectionMediaWithText.vue
- components/FlexibleBlocks.vue
- components/RichText.vue
- components/SectionSpacesList.vue
- components/SimpleCards.vue
Update spacing on components and location detail page.
> fix: spacing review with ux team

- components/Flexible/MediaGallery.vue
- components/MediaGallery/NewLightbox.vue
- stories/MediaGallery_Lightbox.spec.js
- stories/MediaGallery_Lightbox.stories.js
**Component Refactored:** MediaGallery.vue from #403 
**Notes:**
Simple refactor, just using keydown from vue, instead of creating a new function just to listen the press of esc key.
> refactor: instead of doing a function to watch esc key I just used keydown

- components/HeaderMainResponsive.vue
- components/HeaderSmart.vue
- components/NavMenuItemResponsive.vue
Connected to [APPS-1594](https://jira.library.ucla.edu/browse/APPS-1594)
Acceptance Criteria:
> fix: HeaderMainResponsiveRefactor

- layouts/default.vue
works in chrome and edge, but not working as expected in firefox
> feat: adds skip link and main landmark

- gql/queries/HelpTopicList.gql
- pages/help/services-resources/index.vue
Connected to [APPS-1660](https://jira.library.ucla.edu/browse/APPS-1660)
> fix: Add help topics to Services and Resources listing page

- gql/fragments/collections/AllFpbWithNoBanner.gql
- gql/fragments/collections/DefaultFpb.gql
- gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
- gql/fragments/collections/DefaultFpbWithNoCta.gql
- pages/help/services-resources/_slug.vue
Connected to [APPS-1669](https://jira.library.ucla.edu/browse/APPS-1669)
> bugfix: fix form on services and resources page

- components/BannerHeader.vue
- components/BannerText.vue
- components/BlockAmenities.vue
- components/BlockCampusMap.vue
- components/Flexible/Form.vue
- components/FlexibleBlocks.vue
- components/NavBreadcrumb.vue
- components/RichText.vue
- pages/visit/locations/_slug.vue
- updates location-detail page template and relevant components styling
- addresses requests from content editors related to capitalization, image properties, and spacing
> fix: updates location-detail styling

- pages/about/staff/_slug.vue
- pages/visit/locations/_slug.vue
- updates staff detail template styling
- adds visually hidden "More Information" header to flexible page block content for accessibility
> fix: updates staff-detail template styling

- pages/visit/locations/_slug.vue
- Removes "Location and Access" section
- Adds "Building Access" text as section-summary to "Using the Library" section
- Removes unnecessary divider and adjusts spacing after "About" section
> fix: updates location detail template

- .github/workflows/lint-pr.yml
Copies .github/workflows/lint-pr.yml from the meap-website-nuxt repo, adding an actions to require PR labels and semantic titles
> ci: Lint PR labels and titles

- gql/fragments/BlockCardWithImageFragment.gql
- gql/fragments/BlockHighlightFragment.gql
- package-lock.json
- package.json
Connected to [APPS-1805](https://jira.library.ucla.edu/browse/APPS-1805)
feat: update BlockHighlight and CardWithImage fragments and component library
> feat: update fragments and component library

- .env.example
- .github/workflows/ci.yml
- .github/workflows/on-publish.yml
- gql/fragments/BlockMediaGalleryFragment.gql
- modules/sitemapRouteGenerator.js
- nuxt.config.js
- package-lock.json
- package.json
Connected to [APPS-1804](https://jira.library.ucla.edu/browse/APPS-1804)
Check Media Gallery on this page for focal point fix
https://deploy-preview-456--uclalibrary-test.netlify.app/help/services-resources/service-with-all-flexible-page-block-types
Connected to [APPS-1787](https://jira.library.ucla.edu/browse/APPS-1787)
https://deploy-preview-456--uclalibrary-test.netlify.app/sitemap.xml
This PR will add sitemap.xml to the library static site,
https://deploy-preview-23--test-meap.netlify.app/sitemap.xml
To test this locally:
Copy SITEMAP_HOST to .env from .env.example.
Run the following commands:
npm run generate
npm run start
copy the URL from the terminal window and append /sitemap.xml in the browser
> feat: Add focal point package update and nust sitemap module

- gql/fragments/collections/AllFpb.gql
- gql/queries/LocationDetail.gql
Connected to [APPS-1714](https://jira.library.ucla.edu/browse/APPS-1714)
> feat: Update Location entry to use allFpb flexible page block collection

- gql/fragments/collections/AllFpb.gql
- gql/queries/ImpactReportStory.gql
- package-lock.json
- package.json
- pages/impact/_year/_slug.vue
Connected to [APPS-1911](https://jira.library.ucla.edu/browse/APPS-1911)
https://deploy-preview-481--uclalibrary-test.netlify.app/impact/2022/test-main-story
> fix: APPS-1911 Update Main story template to fetch data from Craft

- gql/fragments/BlockAssociatedTopicCardsFragment.gql
- gql/fragments/BlockBannerFeaturedFragment.gql
- gql/fragments/BlockCardWithImageFragment.gql
- gql/fragments/BlockFormFragment.gql
- gql/fragments/BlockHighlightFragment.gql
- gql/fragments/BlockImpactNumbersCarouselFragment.gql
- gql/fragments/BlockMediaGalleryFragment.gql
- gql/fragments/BlockRichTextFragment.gql
- package-lock.json
- package.json
- pages/index.vue
Connected to [APPS-1713](https://jira.library.ucla.edu/browse/APPS-1713)
---
```
<block-associated-topic-cards>
sectionTitle: titleGeneral
sectionSummary: summary
<block-banner-featured>
sectionTitle: titleGeneral
<block-card-with-image>
sectionTitle: titleGeneral
sectionSummary: summary
<block-highlight>
sectionTitle: titleGeneral
sectionSummary: summary
<block-impact-numbers-carousel>
sectionTitle: titleGeneral
<block-media-gallery>
sectionTitle: titleGeneral
sectionSummary: summary
<block-mediaWith-text>
sectionTitle: titleGeneral
sectionSummary: summary
<block-pull-quote>
<block-rich-text>
<block-simple-cards>
sectionTitle: titleGeneral
sectionSummary: summary
<block-call-to-action>
<block-form>
sectionTitle: titleGeneral
sectionSummary: summary
```
---
+ …
> fix: APPS-1713 Add sectionTitle & sectionSummary to FPB collections

- nuxt.config.js
- plugins/data-api.js
> fix: make es keys optional

- .env.example
- cypress/integration/impactmainstory.spec.js
- gql/fragments/BlockMediaGalleryFragment.gql
- gql/fragments/BlockMediaWithTextFragment.gql
- gql/fragments/collections/ImpactReportFpb.gql
- gql/queries/ImpactReportStory.gql
- pages/impact/_year/_slug.vue
Connected to [APPS-1972](https://jira.library.ucla.edu/browse/APPS-1972)
https://deploy-preview-492--uclalibrary-test.netlify.app/impact/2021/ucla-library-reimagined
> fix: Apps 1927 get hero image video from craft in impact report main story

- gql/fragments/BlockCardWithImageFragment.gql
- gql/fragments/BlockHighlightFragment.gql
- gql/fragments/BlockMediaWithTextFragment.gql
- gql/queries/ArticleList.gql
- package-lock.json
- package.json
- pages/impact/_year/_slug.vue
- pages/impact/_year/index.vue
Connected to [APPS-1938](https://jira.library.ucla.edu/browse/APPS-1938)
**Notes:**
This is the related component PR https://github.com/UCLALibrary/ucla-library-website-components/pull/205
This PR will add the title and external url to CardwithImage and highlight
This Pr will enable flexible_bannerfeatured to pass video prop to BannerFeatured component
Initially I wanted to create a smartmedia component , but it needed more, so will create a new ticket for this work.
One more thing I noticed is when I do npm link between repos the responsive-video's opacity is not 1 and hence we see background white. but it works when we do not link the repos using npm.
**Checklist:**
-   [ ] I …
> feat: Fix impact report video

- cypress/integration/articleblogdetailpage.spec.js
- cypress/integration/articlenewsdetailpage.spec.js
- gql/queries/ArticleList.gql
- package-lock.json
- package.json
- pages/about/blogs/_slug.vue
- pages/about/blogs/index.vue
- pages/about/news/_slug.vue
- pages/about/news/index.vue
Connected to [APPS-1510](https://jira.library.ucla.edu/browse/APPS-1510)
+ https://deploy-preview-498--uclalibrary-test.netlify.app/about/news/flexible-page-blocks-are-flexy/
+ https://deploy-preview-498--uclalibrary-test.netlify.app/about/news/test-news-title-test-for-bannertext/
+ https://deploy-preview-498--uclalibrary-test.netlify.app/about/blogs/giraffe/
+ https://deploy-preview-498--uclalibrary-test.netlify.app/about/blogs/test-blog-bannertext/
> fix: Article Detail Page

- gql/fragments/collections/AllFpb.gql
Connected to [APPS-1942](https://jira.library.ucla.edu/browse/APPS-1942)
> fix: APPS-1942 Add BlockImpactNumberCardsFragment to AllFpb collection

- package-lock.json
- package.json
- pages/about/blogs/_slug.vue
- pages/about/news/_slug.vue
the bannerText component will need to be reverted.
> fix: refactor the bannerText byline

- nuxt.config.js
- pages/visit/events-exhibits/_slug.vue
**Notes:**
**Checklist:**
-   [x] I completed any required mobile breakpoint styling
-   [x] I completed any required hover state styling
-   [x] I added notes above about how long it took to build this component
> feat: add router anchor nuxt link function

- layouts/default.vue
- package-lock.json
- package.json
- pages/_.vue
- pages/about/blogs/_slug.vue
- pages/about/news/_slug.vue
- pages/about/policies/_slug.vue
- pages/about/programs/_slug.vue
- pages/help/services-resources/_slug.vue
- pages/impact/_year/_slug.vue
- pages/visit/events-exhibits/_slug.vue
- pages/visit/locations/_slug.vue
Connected to [APPS-1988](https://jira.library.ucla.edu/browse/APPS-1988)
> refactor: APPS-1988 standardize banner styling on all templates

- gql/queries/LocationDetail.gql
- pages/impact/_year/index.vue
Connected to [APPS-1993](https://jira.library.ucla.edu/browse/APPS-1993)
fix: APPS-1993 impact report animation on impact index page is
> fix: APPS-1993 impact report animation

- pages/about/programs/_slug.vue
> fix: do not show associated articles block if there are none

- nuxt.config.js
- package-lock.json
- package.json
- pages/visit/events-exhibits/_slug.vue
- plugins/scrape-formid.client.js
- utils/scrapeFormId.js
Connected to https://jira.library.ucla.edu/browse/APPS-1908
**Notes:**
I had to use nuxt plugins to scrape the id and fetch the form data in mounted hook
> feat: add nuxt util to scrape formid from public libcal calendar page

- pages/impact/_year/index.vue
- adds divider way finder before timeline starts
> fix: add divider before timeline

- package-lock.json
- package.json
- pages/impact/_year/_slug.vue
- change section wrapper in impact report main story to have white background and no padding
> fix: make impact report main story bg white

- gql/queries/ServiceResourceWorkshopSeriesList.gql
- package-lock.json
- package.json
- pages/about/staff/index.vue
- pages/help/services-resources/index.vue
- plugins/data-api.js
- utils/getListingFilters.js
- utils/mergeFilters.js
- utils/searchConfig.js
- utils/sortByTitle.js
Connected to [APPS-2010](https://jira.library.ucla.edu/browse/APPS-2010)
**Notes:**
Filters and search working on staff and services and resource listing pages.
Meet with UX to understand if ES query needs to use AND or OR operator
> fix: APPS-2010 Refactor ES queries

- cypress/integration/servicesresourceslistpage.spec.js
- gql/queries/ServiceResourceWorkshopSeriesList.gql
- package-lock.json
- package.json
- pages/help/services-resources/index.vue
Connected to [APPS-1967](https://jira.library.ucla.edu/browse/APPS-1967)
> feat: APPS-1967 Create Services and Resources listing page

- gql/queries/HelpTopicList.gql
- pages/help/services-resources/index.vue
Connected to [APPS-2030](https://jira.library.ucla.edu/browse/APPS-2030)
> fix: add help topics to services and resources listing

- gql/queries/ServiceResourceWorkshopSeriesList.gql
- pages/help/services-resources/index.vue
Connected to [APPS-2036](https://jira.library.ucla.edu/browse/APPS-2036)
> fix: adds external resource with displayEntry true to all services and resources listing page

- modules/populate/index.js
- modules/populate/populate.server.js
- nuxt.config.js
- package-lock.json
- package.json
- pages/about/blogs/_slug.vue
- pages/about/news/_slug.vue
- pages/about/policies/_slug.vue
- pages/about/programs/_slug.vue
- pages/about/staff/_slug.vue
- pages/about/staff/index.vue
- pages/collections/_slug.vue
- pages/collections/index.vue
- pages/help/_slug.vue
- pages/help/services-resources/_slug.vue
- pages/help/services-resources/index.vue
- pages/impact/_year/_slug.vue
- pages/impact/_year/index.vue
- pages/index.vue
- pages/visit/events-exhibitions/_slug.vue
- pages/visit/events-exhibitions/index.vue
- store/index.js
Connected to [APPS-2017](https://jira.library.ucla.edu/browse/APPS-2017)
Adding concurrency and interval to nuxt.config.js, added populate module to cache queries in Nuxt payload
> feat!: APPS-2017 catchglobalqueries

- cypress/integration/eventseriesdetail.spec.js
- gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
- gql/queries/EventDetail.gql
- gql/queries/EventWorkshopList.gql
- gql/queries/ExhibitionsAndEventsList.gql
- pages/visit/events-exhibitions/_slug.vue
- pages/visit/events-exhibitions/index.vue
Connected to [APPS-1948](https://jira.library.ucla.edu/browse/APPS-1948)
https://deploy-preview-545--uclalibrary-test.netlify.app/visit/events-exhibitions/test-event-series
> feat: Event Series Detail Page

- pages/search_site/index.vue
fix: update to for search results
Links on result cards are working https://deploy-preview-546--uclalibrary-test.netlify.app/search_site
> fix: update to for search results

- gql/queries/GeneralContentDetail.gql
- pages/_.vue
- adds button to banners of general content page
- updates hash lines and divider colors for general content page 
**Checklist:**
> feat: updates general content page with QA

- gql/queries/CollectionsList.gql
- pages/collections/_slug.vue
- pages/collections/index.vue
Connected to [APPS-2057](https://jira.library.ucla.edu/browse/APPS-2057)
- Update computed properties
- Update index page with correct collections link so page is crawled
- CollectionsList.gql mostly reformatted, but added uri
No longer seeing errors in computed properties in devtools
> fix: update collections index and collections detail

- gql/queries/HelpTopicDetail.gql
- pages/help/_slug.vue
Connected to [APPS-2062](https://jira.library.ucla.edu/browse/APPS-2062)
All links work on https://deploy-preview-549--uclalibrary-test.netlify.app/help/help-topic-1/
> fix: help topic page paths

- gql/queries/CollectionsAccessList.gql
- gql/queries/CollectionsList.gql
- pages/collections/access/index.vue
- pages/collections/index.vue
Connected to [APPS-1064](https://jira.library.ucla.edu/browse/APPS-1964)
https://deploy-preview-517--uclalibrary-test.netlify.app/collections
> feat: APPS-1964 Create listing page for Collections

- gql/fragments/BlockMediaGalleryFragment.gql
- gql/fragments/MediaAsset.gql
- gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql
- package-lock.json
- package.json
brings support for video and embedded formats
> feat: Use upgraded MediaGallery/MediaItem

- cypress/integration/exhibitiondetail.spec.js
- gql/queries/EventDetail.gql
- pages/visit/events-exhibitions/_slug.vue
Connected to [APPS-1931](https://jira.library.ucla.edu/browse/APPS-1931)
https://deploy-preview-552--uclalibrary-test.netlify.app/visit/events-exhibitions/fante-asafo-flags
> feat: exhibition detail page

- nuxt.config.js
- package-lock.json
- package.json
- pages/about/staff/index.vue
- pages/help/services-resources/index.vue
- pages/search_site/index.vue
- plugins/data-api.client.js
- plugins/data-api.js
- utils/searchConfig.js
Connected to [APPS-1731](https://jira.library.ucla.edu/browse/APPS-1731)
Using fetch and fetchkey and fetchserver for bookmarked pages with query strings to work.
> feat: APPS-1731 watch query push router

- cypress/integration/askuspage.spec.js
- gql/queries/AskUs.gql
- pages/help/services-resources/ask-us/index.vue
Connected to [APPS-1946](https://jira.library.ucla.edu/browse/APPS-1946)
https://deploy-preview-553--uclalibrary-test.netlify.app/help/services-resources/ask-us/
Test entry: https://test-craft.library.ucla.edu/admin/entries/askUs/42140-ask-us 
Path: /help/services-resources/ask-us
Figma: https://www.figma.com/file/BLO5HP8AphPr0KEacFPjs8/branch/8icgYxEVS0PyIXGnYVgbDB/COPY-of-UI-Pattern-Library-(Client-Facing)-Final?node-id=9563%3A86004
> feat: APPS-1946 Create Ask Us page template

- cypress/integration/endowmentsdetail.spec.js
- gql/fragments/Image.gql
- gql/queries/EndowmentDetail.gql
- pages/support/endowments/_slug.vue
**Notes:**
**Checklist:**
-   [x] I completed any required mobile breakpoint styling
-   [x] I completed any required hover state styling
> feat: Creates endowments detail page

- pages/help/services-resources/ask-us/index.vue
https://deploy-preview-560--uclalibrary-test.netlify.app/help/services-resources/ask-us/ 
updates Ask Us with UX QA
-   [x] UX has reviewed this PR
> feat: updates Ask Us

- gql/queries/EventDetail.gql
- gql/queries/ServiceResourceWorkshopSeriesList.gql
- package-lock.json
- package.json
- pages/_.vue
- pages/about/staff/index.vue
- pages/help/_slug.vue
- pages/help/services-resources/_slug.vue
- pages/help/services-resources/index.vue
- pages/search-site/index.vue
- pages/visit/events-exhibitions/_slug.vue
- plugins/data-api.js
- plugins/elasticsearchplugin.js
- utils/searchConfig.js
Connected to [APPS-2046](https://jira.library.ucla.edu/browse/APPS-2046)
> feat: Update sectionhandle query part, Add external resource to index and perform search on search icon button click

- cypress/integration/eventsexhibitionslist.spec.js
- gql/queries/ExhibitionsAndEventsList.gql
- package-lock.json
- package.json
- pages/visit/events-exhibitions/index.vue
https://deploy-preview-559--uclalibrary-test.netlify.app/visit/events-exhibitions
Connected to [APPS-1968](https://jira.library.ucla.edu/browse/APPS-1968)
**Notes:**
**Checklist:**
-   [ ] I added github label for semantic versioning
> feat: Create events listing page

- gql/fragments/BlockMediaWithTextFragment.gql
- gql/fragments/collections/DefaultFpb.gql
- package-lock.json
- package.json
- upgrades ucla-library-website-components dependency
- changes BlockMediaWithTextFragment to match new data structure
> feat: use improved MediaWithText

- gql/queries/ArticleList.gql
- package-lock.json
- package.json
- pages/about/news/index.vue
- pages/help/services-resources/index.vue
**Notes:**
**Checklist:**
-   [ ] I added github label for semantic versioning
> fix: updates from qa of news listing template

- cypress/integration/resource.spec.js
- cypress/integration/service.spec.js
- gql/queries/ArticleDetail.gql
- gql/queries/CollectionDetail.gql
- gql/queries/EndowmentDetail.gql
- gql/queries/EventDetail.gql
- pages/collections/explore/_slug.vue
- pages/give/endowments/_slug.vue
- pages/help/services-resources/index.vue
- utils/searchConfig.js
Connected to [APPS-2091](https://jira.library.ucla.edu/browse/APPS-2091)
**Notes:**
Add search fields, filters, results fields, and sort fields for the rest of the filter pages.
Additional fixes: Endowments donors on endowment detail page.
> fix: APPS-2091 update search config with filters for the listing pages.

- package-lock.json
- package.json
- utils/searchConfig.js
Connected to [APPS-2044](https://jira.library.ucla.edu/browse/APPS-2044)
**Notes:**
Add Single checkbox for subjectlibrarian on staff page
> feat: APPS-2044 Add Single checkbox for subjectlibrarian on staff page

- gql/queries/EndowmentDetail.gql
- pages/give/endowments/_slug.vue
- pages/search-site/index.vue
- plugins/data-api.js
- utils/searchConfig.js
Connected to [APPS-2012](https://jira.library.ucla.edu/browse/APPS-2012)
> feat: APPS-2012 Site Search Pagination

- cypress/integration/collectiondetailpage.spec.js
- cypress/integration/homepage.spec.js
- gql/queries/EventDetail.gql
- gql/queries/Homepage.gql
- pages/index.vue
- pages/search-site/index.vue
Connected to [APPS-1986](https://jira.library.ucla.edu/browse/APPS-1986)
Homepage https://deploy-preview-561--uclalibrary-test.netlify.app/
> feat:  homepage

- pages/about/staff/index.vue
- utils/flattenTimeLineStructure.js
- utils/searchConfig.js
Connected to [APPS-2045](https://jira.library.ucla.edu/browse/APPS-2045)
A separate ticket exists to design the table structure.
> feat: APPS-2045 group by Academic Depts on staff listing page

- gql/queries/Globals.gql
- layouts/default.vue
- package-lock.json
- package.json
- store/index.js
This PR handles the data and positioning on the page. It currently uses the old version of the SiteNotificationAlert component, but once https://github.com/UCLALibrary/ucla-library-website-components/pull/277 is merged it will look like this:
> feat: Library Alerts

- gql/queries/Homepage.gql
- layouts/error.vue
- pages/index.vue
Connected to [APPS-2077](https://jira.library.ucla.edu/browse/APPS-2077)
> fix: Homepage update section dual masonary

- package-lock.json
- package.json
- static/blockCliccHours.html
- static/blockHours.html
put blocks hours in a good enough state for now.
> fix: update styling of block hours

- package-lock.json
- package.json
chore: update component library to 2.25.1
> chore: update component library

- cypress/integration/homepage.spec.js
- package-lock.json
- package.json
- pages/about/staff/index.vue
chore: update component library 2.25.3
> chore: update component library 2.25.3

- gql/queries/CollectionsAccessList.gql
- gql/queries/CollectionsExploreList.gql
- gql/queries/EventDetail.gql
- gql/queries/ExhibitionsAndEventsList.gql
- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- pages/about/news/_slug.vue
- pages/help/services-resources/_slug.vue
- pages/index.vue
- pages/visit/events-exhibitions/_slug.vue
- pages/visit/events-exhibitions/index.vue
Connected to [APPS-2149](https://jira.library.ucla.edu/browse/APPS-2149)
Adds sectionHandle to queries so that events with display times
> feat: APPS 2149 add date components

- gql/fragments/BlockCallToActionFragment.gql
https://deploy-preview-612--uclalibrary-test.netlify.app/testing-draft-previews
> fix: link URL in BlockCallToAction

- gql/queries/EventDetail.gql
- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- pages/help/services-resources/_slug.vue
- pages/index.vue
- pages/search-site/index.vue
- pages/visit/events-exhibitions/_slug.vue
Connected to [UX-886](https://jira.library.ucla.edu/browse/UX-886)
> feat: add related series to event and workshop detail

- package-lock.json
- package.json
- pages/give/endowments/_slug.vue
- pages/give/endowments/index.vue
This fixes alternative name display is the endowment detail page. Fix for endowment listing will come in the components repo
https://deploy-preview-611--uclalibrary-test.netlify.app/give/endowments/lifu-wang-chinese-cultural-endowment
> fix: alternativeName in endowment detail title

- gql/fragments/BlockBannerFeaturedFragment.gql
- gql/fragments/BlockCardWithImageFragment.gql
- gql/fragments/BlockHighlightFragment.gql
- package-lock.json
- package.json
- pages/impact/_year/_slug.vue
See flexible blocks at the bottom of the page: https://deploy-preview-621--uclalibrary-test.netlify.app/impact/2022/test-main-story/
> chore: update component library and queries

- package-lock.json
- package.json
- pages/visit/locations/index.vue
Connected to [APPS-2143](https://jira.library.ucla.edu/browse/APPS-2143)
> fix: libcal hours display

- modules/indexAliasGenerator.js
- modules/swapAliasIndexGenerator.js
- nuxt.config.js
- pages/about/news/index.vue
- pages/about/staff/index.vue
- pages/help/services-resources/index.vue
- plugins/elasticsearchplugin.js
Connected to [APPS-2051](https://jira.library.ucla.edu/browse/APPS-2051)
Removed fetchstate from the template.
> fix: fix partial indexing issue

- gql/fragments/BlockCardWithImageFragment.gql
- gql/fragments/BlockHighlightFragment.gql
- gql/queries/ExhibitionsAndEventsList.gql
- gql/queries/LocationDetail.gql
- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- pages/visit/locations/_slug.vue
Connected to [APPS-2171](https://jira.library.ucla.edu/browse/APPS-2171)
https://deploy-preview-627--uclalibrary-test.netlify.app/visit/locations/young-research-library/
Computed property was setting ongoing value
> fix: Fix "ongoing" in Exhibitions

- .github/workflows/auto-build.yml
- .github/workflows/manual-site-build.yml
fixes to daily build workflow, run it twice (noon and midnight PST; 1 am & 1 pm PDT)
> ci: fix daily build workflow

- assets/styles/global.scss
- pages/about/news/index.vue
- pages/search-site/index.vue
Connected to [APPS-2175](https://jira.library.ucla.edu/browse/APPS-2175)
- adds global styles for site search and listing page results
- adds error text to news index to match site search format
> feat: add site search styling and text

- gql/queries/CollectionsExploreList.gql
- gql/queries/EventDetail.gql
- pages/about/news/index.vue
- pages/collections/explore/index.vue
- plugins/data-api.js
- utils/searchConfig.js
Connected to [APPS-2053](https://jira.library.ucla.edu/browse/APPS-2053)
https://deploy-preview-636--uclalibrary-test.netlify.app/collections/explore
`EventDetail.gql` just was linted
> feat: explore collections search and filters

- gql/queries/AskUs.gql
- pages/visit/locations/_slug.vue
Connected to [APPS-2188](https://jira.library.ucla.edu/browse/APPS-2188)
Connected to [UX-925](https://jira.library.ucla.edu/browse/UX-925)
- adds summary to ask us single
- updates angle and lightens gradient overlay on location banners
> feat: adds ask us summary, updates location banner gradient

- gql/queries/ProgramDetail.gql
- gql/queries/ProgramsList.gql
- pages/about/news/index.vue
- pages/about/programs/_slug.vue
- pages/about/programs/index.vue
Connected to [APPS-2110](https://jira.library.ucla.edu/browse/APPS-2110)
https://deploy-preview-634--uclalibrary-test.netlify.app/about/programs/
> feat: Apps 2110 programs filters

- gql/queries/EndowmentList.gql
- pages/give/endowments/_slug.vue
- pages/give/endowments/index.vue
- utils/searchConfig.js
Connected to [APPS-2155](https://jira.library.ucla.edu/browse/APPS-2155)
https://deploy-preview-644--uclalibrary-test.netlify.app/give/endowments/
> feat: endowment search filters

- gql/queries/CollectionsAccessList.gql
Connected to [APPS-2185](https://jira.library.ucla.edu/browse/APPS-2185)
https://deploy-preview-646--uclalibrary-test.netlify.app/collections/access/
> fix: APPS-2185 Alphabetize Entries on Access Collections Page

- pages/search-site/index.vue
Connected to [APPS-2154](https://jira.library.ucla.edu/browse/APPS-2154)
+ https://deploy-preview-651--uclalibrary-test.netlify.app/search-site/?q=program
+ https://deploy-preview-651--uclalibrary-test.netlify.app/search-site/?q=service
> fix: APPS-2154 Add space to category in SearchResult component

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- cypress/e2e/articlenewslistingpage.cy.js
- cypress/e2e/collectionsexplorepage.cy.js
- cypress/e2e/locationlistpage.cy.js
- cypress/e2e/servicesresourceslistpage.cy.js
- cypress/e2e/stafflistingpage.cy.js
Connected to [APPS-2150](https://jira.library.ucla.edu/browse/APPS-2150)
> fix: Add tests for search filters on listing pages

- package-lock.json
- package.json
- pages/about/news/index.vue
- pages/about/programs/index.vue
- pages/about/staff/index.vue
- pages/collections/explore/index.vue
- pages/give/endowments/index.vue
- pages/help/services-resources/index.vue
- pages/search-site/index.vue
- pages/visit/events-exhibitions/index.vue
- pages/visit/locations/index.vue
Connected to [APPS-2142](https://jira.library.ucla.edu/browse/APPS-2142)
> feat: APPS-2142 Update Search placeholders

- pages/give/endowments/_slug.vue
Connected to [APPS-2159](https://jira.library.ucla.edu/browse/APPS-2159)
SubjectArea link connects to a filtered search on the endowment Listing page
+ https://deploy-preview-659--uclalibrary-test.netlify.app/give/endowments/the-gold-shield-marjorie-alice-lenz-endowed-collection-in-fashion-and-costume-design/
+ https://deploy-preview-659--uclalibrary-test.netlify.app/give/endowments/lifu-wang-chinese-cultural-endowment/
> feat: APPS-2159 Replace links with filtered search views endowment detail

- pages/visit/locations/_slug.vue
Connected to [APPS-2159](https://jira.library.ucla.edu/browse/APPS-2159)
Location detail staff directory link
+ https://deploy-preview-658--uclalibrary-test.netlify.app/visit/locations/biomed/
+ https://deploy-preview-658--uclalibrary-test.netlify.app/visit/locations/data-science-center/
> feat: APPS-2159 Replace location detail staff directory link with filtered search

- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- pages/help/services-resources/_slug.vue
- pages/search-site/index.vue
fix: update services slug page for image logic
> fix: update services slug page for image logic

- gql/queries/EventDetail.gql
- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- pages/help/services-resources/_slug.vue
- pages/visit/events-exhibitions/_slug.vue
Connected to [APPS-2203](https://jira.library.ucla.edu/browse/APPS-2203)
Workshop Series with Associated Topics: https://deploy-preview-672--uclalibrary-test.netlify.app/help/services-resources/radical-films-a-weekend-with-robert-carl-cohen
Event Series with Associated Topics: https://deploy-preview-672--uclalibrary-test.netlify.app/visit/events-exhibitions/family-flicks/
> fix: event series and workshop series associated topic links

- pages/collections/access/index.vue
- pages/collections/explore/index.vue
Connected to [APPS-2205](https://jira.library.ucla.edu/browse/APPS-2205)
> fix: add aliases for collections pages

- pages/about/programs/_slug.vue
- pages/visit/locations/_slug.vue
- pages/visit/locations/index.vue
Connected to [APPS-2202](https://jira.library.ucla.edu/browse/APPS-2202)
https://deploy-preview-671--uclalibrary-test.netlify.app/visit/locations
https://deploy-preview-671--uclalibrary-test.netlify.app/visit/locations/biomed
> fix: APPS-2202 Further identify the SEE MORE buttons on each page

- gql/queries/EventDetail.gql
- gql/queries/LocationDetail.gql
- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- package-lock.json
- package.json
- pages/index.vue
- pages/visit/events-exhibitions/index.vue
- utils/searchConfig.js
Connected to [APPS-2207](https://jira.library.ucla.edu/browse/APPS-2207)
> fix: search working, event titles, disappeared events from prod

- .github/workflows/auto-build.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
required secrets:
AWS_S3_BUCKET
AWS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION
also stops trying to invoke auto-build.yml from on-release.yml; just copy the job over instead
> ci: deploy to S3

- app/router.scrollBehavior.js
- nuxt.config.js
- pages/_.vue
- pages/about/news/_slug.vue
- pages/about/news/index.vue
- pages/about/policies/_slug.vue
- pages/about/programs/_slug.vue
- pages/about/programs/index.vue
- pages/about/staff/_slug.vue
- pages/about/staff/index.vue
- pages/collections/explore/_slug.vue
- pages/collections/explore/index.vue
- pages/give/endowments/_slug.vue
- pages/give/endowments/index.vue
- pages/help/_slug.vue
- pages/help/services-resources/_slug.vue
- pages/help/services-resources/index.vue
- pages/impact/_year/_slug.vue
- pages/impact/_year/index.vue
- pages/index.vue
- pages/search-site/index.vue
- pages/visit/events-exhibitions/_slug.vue
- pages/visit/events-exhibitions/index.vue
- pages/visit/locations/_slug.vue
- pages/visit/locations/index.vue
Connected to [APPS-2128](https://jira.library.ucla.edu/browse/APPS-2128)
The scroll will always go to the top of page if to.fullpath is listing pages and or saveposition y offset is greater than 2000px.
> fix: scroll behaviour when using back/forward browser buttons

- gql/queries/ExhibitionsAndEventsList.gql
- pages/visit/events-exhibitions/index.vue
Connected to [APPS-2204](https://jira.library.ucla.edu/browse/APPS-2204)
adds workshop series to event series and exhibitions section of event listing single
https://deploy-preview-689--uclalibrary-test.netlify.app/visit/events-exhibitions
> feat: add workshop series to ongoing events section

- gql/queries/ServiceResourceWorkshopSeriesList.gql
- pages/help/services-resources/index.vue
Connected to [APPS-2298](https://jira.library.ucla.edu/browse/APPS-2298)
> fix: index all external resources and only show with displayentry field yes on listing page

- pages/about/news/index.vue
- pages/about/programs/index.vue
- pages/about/staff/index.vue
- pages/collections/explore/index.vue
- pages/search-site/index.vue
- pages/visit/locations/index.vue
- plugins/data-api.js
- plugins/elasticsearchplugin.js
- utils/getListingFilters.js
- utils/searchConfig.js
Connected to [APPS-2293](https://jira.library.ucla.edu/browse/APPS-2293)
> feat: Add type filter to site search

- static/_redirects
should fix https://jira.library.ucla.edu/browse/APPS-2325
> fix: fix events-exhibitions redirect

- pages/visit/events-exhibitions/index.vue
Connected to [APPS-2325](https://jira.library.ucla.edu/browse/APPS-2325)
> fix: check array length for eventType

- gql/queries/Homepage.gql
Connected to [APPS-2331](https://jira.library.ucla.edu/browse/APPS-2331)
> fix: APPS-2331 firx breaking "View Article" button for internal links

- gql/queries/Homepage.gql
- pages/index.vue
Connected to [APPS-2331](https://jira.library.ucla.edu/browse/APPS-2331)
Fixing the button broke the article links. This PR fixes all the links
> fix: APPS-2331

- utils/flattenTimeLineStructure.js
Connected to [APPS-2301](https://jira.library.ucla.edu/browse/APPS-2301)
> fix: add forward slash to uri

- gql/queries/Homepage.gql
- pages/index.vue
Connected to [APPS-2331](https://jira.library.ucla.edu/browse/APPS-2331)
> fix: APPS-2331 fix button link on homepage featured news

- cypress/e2e/homepage.cy.js
- cypress/e2e/servicesresourceslistpage.cy.js
- package-lock.json
- package.json
- pages/help/services-resources/index.vue
- utils/isRelativeLink.js
Connected to [APPS-2363](https://jira.library.ucla.edu/browse/APPS-2363)
Updates the component library to fix the Alphabetical Browseby pagination component to include the letter "Y"
> fix: update component library to 2.37.4

- package-lock.json
- package.json
Connected to [APPS-2375](https://jira.library.ucla.edu/browse/APPS-2375)
> fix: APPS-2375 update component version to 2.37.5

- pages/about/jobs/staff-academic-jobs/index.vue
- pages/about/student-opportunities/index.vue
- utils/fixUri.js
Connected to [APPS-2334](https://jira.library.ucla.edu/browse/APPS-2334)
> fix: associated location links from job listings

- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- package-lock.json
- package.json
- pages/help/services-resources/_slug.vue
Connected to [APPS-2380](https://jira.library.ucla.edu/browse/APPS-2380)
https://deploy-preview-716--uclalibrary-test.netlify.app/help/services-resources/fashion-test-fpb-refactor
> fix: APPS-2380_fix-button-banner-header

- package-lock.json
- package.json
Connected to [APPS-2386](https://jira.library.ucla.edu/browse/APPS-2386)
> fix: update component library package version to 2.38.2

- pages/visit/events-exhibitions/index.vue
- plugins/data-api.js
- utils/searchConfig.js
> fix: event listing w/ keyword date sort and filter

- cypress.config.js
- cypress/e2e/homepage.cy.js
- cypress/support/commands.js
- cypress/support/e2e.js
- nuxt.config.ts
- package.json
- pnpm-lock.yaml
Connected to [APPS-2278](https://jira.library.ucla.edu/browse/APPS-2278)
> chore: install cypress and configure and test homepage basic test

- .eslintrc
- package.json
- pnpm-lock.yaml
Connected to [APPS-2278](https://jira.library.ucla.edu/browse/APPS-2278)
> chore: add eslint

- app.vue
- nuxt.config.ts
- plugins/add-library-website-vue-components.js
Connected to [APPS-2383](https://jira.library.ucla.edu/browse/APPS-2383)
> feat: APPS-2383 test local component library

- assets/styles/global.scss
- nuxt.config.ts
- package.json
- pnpm-lock.yaml
Connected to [APPS-2402](https://jira.library.ucla.edu/browse/APPS-2402)
> chore: APPS-2402 add global styles and design-token package

- modules/indexAliasGenerator.js
Connected to [APPS-2328](https://jira.library.ucla.edu/browse/APPS-2328) & [APPS-2376](https://jira.library.ucla.edu/browse/APPS-2376)
> feat: APPS-2376 & APPS-2328 Add site-search-diacritics & stemming

- composables/removeEmpties.js
- gql/fragments/BlockAssociatedTopicCardsFragment.gql
- gql/queries/EventWorkshopList.gql
- gql/queries/ExhibitionsAndEventsList.gql
- gql/queries/ExhibitionsAndEventsListSingle.gql
- gql/queries/FooterPrimaryItems.gql
- gql/queries/FooterSockItems.gql
- gql/queries/HeaderMainMenuItems.gql
- gql/queries/MenuItems.gql
- layouts/default.vue
- nuxt.config.ts
- package.json
- plugins/init.server.js
- pnpm-lock.yaml
- store/globals.js
Connected to [APPS-2399](https://jira.library.ucla.edu/browse/APPS-2399)
[APPS-2399]: https://uclalibrary.atlassian.net/browse/APPS-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2399 add pinia

- gql/fragments/BlockAssociatedTopicCardsFragment.gql
- nuxt.config.ts
- package.json
- plugins/craft.js
- pnpm-lock.yaml
- store/globals.js
Connected to [APPS-2425](https://jira.library.ucla.edu/browse/APPS-2425)
[APPS-2425]: https://uclalibrary.atlassian.net/browse/APPS-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2425 add craft plugin

- data/mock/BlockMediaWithText.js
- data/mock/Media.js
- data/mock/mock.js
- layouts/default.vue
- nuxt.config.ts
- package.json
- pages/components.vue
- plugins/browser-events.client.js
- plugins/init.server.js
- pnpm-lock.yaml
- stores/GlobalStore.js
refactor pinia to match with component library and add remaining components
> fix: refactor pinia to match with component library and add remaining components

- layouts/error.vue
- plugins/data-api.js
Connected to [APPS-2421](https://jira.library.ucla.edu/browse/APPS-2421)
[APPS-2421]: https://uclalibrary.atlassian.net/browse/APPS-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2421   Tweak search results to boost library content over libguides

- static/_redirects
https://uclalibrary.atlassian.net/browse/APPS-2476
https://uclalibrary.atlassian.net/browse/APPS-2475
> fix: add redirects

- static/_redirects
Connected to [APPS-2505](https://jira.library.ucla.edu/browse/APPS-2505)
[APPS-2505]: https://uclalibrary.atlassian.net/browse/APPS-2505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Add redirect to libwizard

- layouts/error.vue
- nuxt.config.js
- pages/about/policies/_slug.vue
- static/_redirects
First tried netlify redirects, It did not work, nuxt build creates 404 pages , so netlify does not redirect
Second tried to use vue router extras redirect option, could not make it work
Third, this worked, used nuxt redirect option from nuxt context.
> fix: APPS-2505 

- cypress/e2e/homepage.cy.js
- plugins/data-api.js
Connected to [APPS-2520](https://jira.library.ucla.edu/browse/APPS-2520)
First name or last name searches were not returning the right results.
[APPS-2520]: https://uclalibrary.atlassian.net/browse/APPS-2520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove * postfix for fuzzy searches

- .github/workflows/ci.yml
Connected to [APPS-2501](https://jira.library.ucla.edu/browse/APPS-2501)
[APPS-2501]: https://uclalibrary.atlassian.net/browse/APPS-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: replace main with nuxt3.x to be deployed to nuxt3.x netlify site when pull request is merged to nuxt3.x

- .github/workflows/ci.yml
Connected to [APPS-2501](https://jira.library.ucla.edu/browse/APPS-2501)
[APPS-2501]: https://uclalibrary.atlassian.net/browse/APPS-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ci update publish directory

- package-lock.json
- package.json
**Notes:**
**Checklist:**
-   [ ] I added github label for semantic versioning
> fix: update search via clear button (components update)

- .github/workflows/percy.yml
- error.vue
- modules/init.js
- package.json
- pages/about/reports/news/[slug].vue
- pages/about/reports/news/index.vue
- pnpm-lock.yaml
- server/api/fetchNitroStorageCraftFooterPrimaryData.js
- server/api/fetchNitroStorageCraftFooterSockData.js
- server/api/fetchNitroStorageCraftGlobalData.js
- server/api/fetchNitroStorageCraftHeaderData.js
Enable github branch protection on nuxt3.x
> fix: update version and comment some code

- .github/workflows/auto-build.yml
Fixing the bug reported by Courtney
Good morning!  [Athena Jackson's staff profile](https://www.library.ucla.edu/about/staff/athena-n-jackson) has been published, however she doesn't appear in the directory listing when searching or browsing for her. Does this take a while to update?
> fix: es temp index env for libguides tem prefix is added now

- .github/workflows/auto-build.yml
- .github/workflows/ci.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
- .github/workflows/setup-workspace/action.yml
- .vscode/settings.json
- cypress/e2e/articlenewsdetailpage.cy.js
- cypress/e2e/articlenewslistingpage.cy.js
- cypress/e2e/homepage.cy.js
- gql/queries/ArticleDetail.gql
- gql/queries/ArticleList.gql
- layouts/default.vue
- modules/finalize.js
- modules/init.js
- nuxt.config.ts
- package.json
- pages/about/news/[slug].vue
- pages/about/news/index.vue
- pages/about/reports/news/[slug].vue
- pages/about/reports/news/index.vue
- pages/index.vue
- pnpm-lock.yaml
- server/api/fetchNitroStorageCraftFooterPrimaryData.js
- server/api/fetchNitroStorageCraftFooterSockData.js
- server/api/fetchNitroStorageCraftGlobalData.js
- server/api/fetchNitroStorageCraftHeaderData.js
- stores/GlobalStore.js
- utils/getListingFilters.js
- utils/queryFilterHasValues.js
- utils/searchConfig.js
Connected to [APPS-2580](https://jira.library.ucla.edu/browse/APPS-2580)
Revisit elastic search and sitemap, once more detail pages and listing pages and search is working on the listing page
[APPS-2580]: https://uclalibrary.atlassian.net/browse/APPS-2580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2580 Add elastic search nuxt modules for index creation and sitemap module

- .github/workflows/percy.yml
- .github/workflows/setup-workspace/action.yml
> ci: Fix percy token name for nuxt3

- .github/workflows/percy.yml
- .github/workflows/setup-workspace/action.yml
> ci: Fix add percy branch for the token

- cypress/e2e/collectiondetailpage.cy.js
- cypress/e2e/eventseriesdetail.cy.js
- static/_redirects
Connected to [APPS-2625](https://jira.library.ucla.edu/browse/APPS-2625)
[APPS-2625]: https://uclalibrary.atlassian.net/browse/APPS-2625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add redirect to subject librarian

- cypress/e2e/policiesdetailpage.cy.js
- cypress/e2e/policieslistpage.cy.js
- gql/queries/PoliciesList.gql
- gql/queries/PolicyDetail.gql
- package.json
- pages/[...slug].vue
- pages/about/news/[slug].vue
- pages/about/news/index.vue
- pages/about/policies/[slug].vue
- pages/about/policies/index.vue
- pages/give/endowments/[slug].vue
- pages/help/[slug].vue
- pages/help/services-resources/[slug].vue
- pages/impact/[year]/[slug].vue
- pages/impact/[year]/index.vue
- pages/visit/locations/[slug].vue
- pnpm-lock.yaml
Connected to [APPS-2645](https://jira.library.ucla.edu/browse/APPS-2645)
**Page/Pages Created/updated:** 
- /about/policies/[slug].vue
**Notes:**
- Noted that page anchors were not displaying 
- `h2Array` ref used in `onMounted` hook needed to be updated
- Anchors may still not display for pages that have missing section headings/titles
- Headings for nested FlexibleBlocks components are missing
- Follow-up ticket: https://uclalibrary.atlassian.net/browse/APPS-2637
**Checklist:**
-   [ ] I added notes above about how long it took to build …
> feat: APPS-2645 Add Policy Details page

- cypress/e2e/jobstudentopportunities.cy.js
- pages/about/student-opportunities/index.vue
Connected to [APPS-2644](https://jira.library.ucla.edu/browse/APPS-2644)
**Page/Pages Created/updated:**
- /about/student-opportunities/index.vue
**Checklist:**
[APPS-2644]: https://uclalibrary.atlassian.net/browse/APPS-2644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2644 Add Student Opportunities page

- cypress/e2e/collectiondetailpage.cy.js
- gql/queries/CollectionDetail.gql
- pages/about/news/[slug].vue
- pages/collections/explore/[slug].vue
Connected to [APPS-2643](https://jira.library.ucla.edu/browse/APPS-2643)
**Page/Pages Created/updated:** 
- /collections/explore/_slug.vue
**Notes:**
- Nested media galleries (half and full width, in FlexibleBlocks components) are missing headings and body text
- Block CTA background theme is dark instead of light
- Issues have been added to FlexibleBlock follow-up/bug ticket: https://uclalibrary.atlassian.net/browse/APPS-2637
**Checklist:**
-   [ ] UX has reviewed …
> feat: APPS-2643 Add Collections Explore Details page

- cypress/e2e/collectionsaccesspage.cy.js
- pages/collections/access/index.vue
Connected to [APPS-2651](https://jira.library.ucla.edu/browse/APPS-2651)
**Page/Pages Created/updated:** /collections/access/index.vue from #2651
**Notes:**
Enabling as much elastic search indexing logic as possible
**Checklist:**
-   [X ] I double checked it looks like the designs
-   [ X] I included a working spec file
[APPS-2651]: https://uclalibrary.atlassian.net/browse/APPS-2651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> feat: enable indexing

- cypress/e2e/collectionlistpage.cy.js
- gql/queries/CollectionsExploreList.gql
- gql/queries/CollectionsList.gql
- gql/queries/EndowmentList.gql
- package.json
- pages/about/news/index.vue
- pages/collections/access/index.vue
- pages/collections/index.vue
- pages/visit/locations/index.vue
- pnpm-lock.yaml
Connected to [APPS-2622](https://uclalibrary.atlassian.net/browse/APPS-2642)
https://www.library.ucla.edu/collections
https://deploy-preview-792--uclalibrary-test-nuxt3x.netlify.app/collections#section-title---featured-collections
**Page/Pages Created/updated:** `pages/collections/index.vue`
**Notes:**
**Checklist:**
-   [x] I included a working spec file …
> feat: APPS-2622 Add Collections Index / List page

- pages/collections/index.vue
Connected to: [APPS-2663](https://uclalibrary.atlassian.net/jira/software/c/projects/APPS/boards/12?selectedIssue=APPS-2663)
https://www.youtube.com/watch?v=-m3uq4qDhXc
Tested locally in Craft
[APPS-2663]: https://uclalibrary.atlassian.net/browse/APPS-2663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: collections index enable preview

- cypress/e2e/programdetailpage.cy.js
- gql/queries/CollectionsExploreList.gql
- gql/queries/ProgramDetail.gql
- package.json
- pages/about/programs/[slug].vue
- pnpm-lock.yaml
Connected to [APPS-2661](https://jira.library.ucla.edu/browse/APPS-2661)
**Page/Pages Created/updated:** 
- /about/programs/[slug].vue
Previews:
- https://deploy-preview-796--uclalibrary-test-nuxt3x.netlify.app/about/programs/digital-library-program
- https://deploy-preview-796--uclalibrary-test-nuxt3x.netlify.app/about/programs/campus-library-instructional-computing-commons-clicc
**Checklist:**
-   [x] I assigned this PR to someone …
> feat: APPS-2661 Add programs slug page

- cypress/e2e/endowmentslist.cy.js
- pages/about/news/index.vue
- pages/collections/access/index.vue
- pages/give/endowments/index.vue
Connected to [APPS-2655](https://jira.library.ucla.edu/browse/APPS-2655)
**Page updated:**
- /give/endowments/index.vue
Sample: https://deploy-preview-797--uclalibrary-test-nuxt3x.netlify.app/give/endowments
Notes: 
We faced this error only on the static site, https://github.com/vuejs/core/issues/5657
To fix this we had used v-show instead of v-if directive in the template, so followed what we have on news and collection ES templates
**Checklist:**
-   [x] I included a working spec file
-   [ ] UX has …
> feat: APPS-2655 Enable ES on Endowments Listing page

- cypress/e2e/locationlistpage.cy.js
- pages/visit/locations/index.vue
Connected to [APPS-2653](https://jira.library.ucla.edu/browse/APPS-2653)
**Page/Pages Created/updated:** /visit/locations/index.vue from #2653
**Notes:**
In progress, currently missing filters, suspect correct data is not being returned from getListingFilters?
This took me 4 hours (so far) to build this.
**Checklist:**
[APPS-2653]: …
> feat: APPS-2653 Enable ES Location Listing page

- .github/workflows/percy.yml
- cypress/e2e/endowmentslist.cy.js
- cypress/e2e/eventsexhibitionslist.cy.js
- cypress/e2e/locationlistpage.cy.js
possible fix for https://github.com/UCLALibrary/library-website-nuxt/actions/runs/8993470444/job/24705320166
> fix: cypress errors on nuxt3 percy check

- cypress/e2e/eventsexhibitionslist.cy.js
- cypress/e2e/staffdetailpage.cy.js
- gql/queries/StaffDetail.gql
- package.json
- pages/about/staff/[slug].vue
- pnpm-lock.yaml
Connected to [APPS-2666](https://jira.library.ucla.edu/browse/APPS-2666)
**Page/Pages Created/updated:** /about/staff/[slug].vue from #{APPS-2666}
**Notes:**
In progress 
This took me 8-12 hours (so far) to build this, including time to study patterns in other [slug].vue page refactors, time to fix page tests which seem to fail due to long loads times, and time to fix data that had been refactored in the child components of this page
**Checklist:**
-   [X ] I included a working spec file
-   [ X] I added notes above about how long it took to build this …
> feat: APPS-2666 Migrate slug/detail template to nuxt3.x for route /about/staff/[slug].vue

- cypress/e2e/user_agent_spec.js
- netlify.toml
- netlify/edge-functions/blockUserAgents.js
- static/robots.txt
Connected to [APPS-2678](https://jira.library.ucla.edu/browse/APPS-2678)
**Notes:**
Copied new bot traffic. blocking logic from nuxt2 to nuxt3 branch, took less than an hour so far.
**Checklist:**
-  [X] I added github label for semantic versioning
-   [X] I added notes above about how long it took to build this component
[APPS-2678]: https://uclalibrary.atlassian.net/browse/APPS-2678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This change has been working on main …
> chore: APPS-2678 Update nuxt3.x branch with the new changes in main

- nuxt.config.ts
- package.json
- pnpm-lock.yaml
Connected to [APPS-2712](https://jira.library.ucla.edu/browse/APPS-2712)
- Add [Google Tags Manager package](https://nuxt.com/modules/nuxt-gtm) to Nuxt3 branch
- Add [GTM ID](https://github.com/UCLALibrary/library-website-nuxt/pull/285/files) to Nuxt config
**Checklist:**
-   [x] I added notes
[APPS-2712]: https://uclalibrary.atlassian.net/browse/APPS-2712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: APPS-2712 Add GoogleTagsManager to Nuxt3

- .github/workflows/nuxt3x.yml
This file will help test nuxt3.x branch on stage with production data
> ci: Create nuxt3x.yml

- gql/fragments/BlockBannerFeaturedFragment.gql
- package.json
- pages/index.vue
- pnpm-lock.yaml
Connected to [PR 513](https://github.com/UCLALibrary/ucla-library-website-components/pull/513)
> fix: Update component library & fpb banner featured query to correspond with component PR 513

- pages/about/staff/index.vue
Connected to [APPS-2722](https://jira.library.ucla.edu/browse/APPS-2722)
**Notes:**
Small change to add a condition to the v-show statement
**Checklist:**
-   [X ] I added github label for semantic versioning
-   [ X] I included a working spec file
[APPS-2722]: https://uclalibrary.atlassian.net/browse/APPS-2722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2722 fix section-wrapper vshow statement on staff listing page

- pages/visit/events-exhibitions/index.vue
Connected to [APPS-2721](https://uclalibrary.atlassian.net/jira/software/c/projects/APPS/boards/12?issueParent=99132%2C99120&selectedIssue=APPS-2721)
[APPS-2721]: https://uclalibrary.atlassian.net/browse/APPS-2721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2721 fix past events filter

- .github/workflows/nuxt3x.yml
Replace workspace action with pnpm setup
Connected to [APPS-2724](https://jira.library.ucla.edu/browse/APPS-2724)
[APPS-2724]: https://uclalibrary.atlassian.net/browse/APPS-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: update nuxt3x.yml

- cypress/e2e/locationlistpage.cy.js
- cypress/e2e/programslistpage.cy.js
- pages/about/news/index.vue
- pages/about/programs/index.vue
- pages/visit/locations/index.vue
- utils/parseFilters.js
Connected to [APPS-2725](https://jira.library.ucla.edu/browse/APPS-2725)
**Notes:**
Created a utils file for parsefilters and refactored the other searchs, + updated test files
This took 4-8 hours, 4ish hours of writing code and running tests, and 2-4 hours of troubleshooting and googling methods used by nuxt to set params for search and communicating findings with team
**Checklist:**
-   [X ] I double checked it looks like the designs
-   [ X] I included a working spec file
-   [ X] I added notes above about how long it took to build this component
-   [ ] I assigned this PR to someone to …
> fix: APPS-2725 queries on news page

- cypress/e2e/stafflistingpage.cy.js
- pages/about/staff/index.vue
- pages/visit/events-exhibitions/index.vue
Connected to [APPS-2726](https://jira.library.ucla.edu/browse/APPS-2726)
[APPS-2726]: https://uclalibrary.atlassian.net/browse/APPS-2726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: APPS-2726 create clean search url for staff

- .gitignore
- cypress/e2e/collectionsexplorepage.cy.js
- pages/collections/explore/index.vue
Connected to [APPS-2727](https://jira.library.ucla.edu/browse/APPS-2727)
**Page(s) updated:** 
- /collections/explore/index.vue
**Preview:** 
- https://deploy-preview-826--uclalibrary-test-nuxt3x.netlify.app/collections/explore
**Checklist:**
-   ~~[ ] I double checked it looks like the designs~~
-   ~~[ ] I completed any required mobile breakpoint styling~~
-   ~~[ ] I completed any required hover state styling~~
-   ~~[ ] I included a working spec file~~
-   ~~[ ] I added notes above about how long it took to build this component~~
-   ~~[ ] UX has reviewed this PR~~
[APPS-2727]: https://uclalibrary.atlassian.net/browse/APPS-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
> refactor: APPS-2727 Clean URL for CollectionsExplore

- cypress/e2e/servicesresourceslistpage.cy.js
- pages/help/services-resources/index.vue
Connected to [APPS-2728](https://jira.library.ucla.edu/browse/APPS-2728)
**Page(s) updated:**
- /help/services-resources/index.vue
**Preview:**
- https://deploy-preview-830--uclalibrary-test-nuxt3x.netlify.app/help/services-resources
**Checklist:**
-   ~~[ ] I double checked it looks like the designs~~
-   ~~[ ] I completed any required mobile breakpoint styling~~
-   ~~[ ] I completed any required hover state styling~~
-   ~~[ ] I included a working spec file~~
-   ~~[ ] I added notes above about how long it took to build this component~~
-   ~~[ ] UX has reviewed this PR~~
[APPS-2728]: https://uclalibrary.atlassian.net/browse/APPS-2728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> refactor: APPS-2728 Clean URL for ServicesResources

- pages/search-site/index.vue
Connected to [APPS-2729](https://jira.library.ucla.edu/browse/APPS-2729)
**Page/Pages Created/updated:** /search-site/index.vue from #APPS-2729
**Checklist:**
-   [X] I added github label for semantic versioning
~~- [ ] I completed any required mobile breakpoint styling~~
~~-   [ ] I completed any required hover state styling~~
~~-   [ ] I included a working spec file~~
~~-   [ ] I added notes above about how long it took to build this component~~
~~-   [ ] UX has reviewed this PR~~
~~-   [ ] I assigned this PR to someone to review~~
[APPS-2729]: https://uclalibrary.atlassian.net/browse/APPS-2729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2729 update search site query

- cypress/e2e/eventsexhibitionslist.cy.js
- pages/visit/events-exhibitions/index.vue
Connected to [APPS-2730](https://jira.library.ucla.edu/browse/APPS-2730)
https://deploy-preview-832--uclalibrary-test-nuxt3x.netlify.app/visit/events-exhibitions
[APPS-2730]: https://uclalibrary.atlassian.net/browse/APPS-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: APPS-2730 create clean search url for events exhibition

- stores/GlobalStore.js
Connected to [APPS-2769](https://jira.library.ucla.edu/browse/APPS-2769)
Notes:
This PR will fix footer data not appearing issue
[APPS-2769]: https://uclalibrary.atlassian.net/browse/APPS-2769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add ref value for the footer

- gql/queries/ServiceOrResourceOrWorkshopDetail.gql
- layouts/default.vue
- pages/about/news/[slug].vue
- pages/about/news/index.vue
- pages/collections/index.vue
- pages/help/[slug].vue
- pages/help/services-resources/index.vue
- pages/visit/events-exhibitions/index.vue
- plugins/update-library-alert.client.js
Connected to [APPS-2778](https://jira.library.ucla.edu/browse/APPS-2778)
[APPS-2779](https://jira.library.ucla.edu/browse/APPS-2779)
[APPS-2778]: https://uclalibrary.atlassian.net/browse/APPS-2778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-2779]: https://uclalibrary.atlassian.net/browse/APPS-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: es filters

- package.json
- pages/about/jobs/staff-academic-jobs/index.vue
- pages/about/student-opportunities/index.vue
- pnpm-lock.yaml
- utils/fixUri.js
Connected to [APPS-2780](https://jira.library.ucla.edu/browse/APPS-2780)
Connected to [APPS-2781](https://jira.library.ucla.edu/browse/APPS-2781)
Connected to [APPS-2802](https://jira.library.ucla.edu/browse/APPS-2802)
[APPS-2780]: https://uclalibrary.atlassian.net/browse/APPS-2780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-2781]: https://uclalibrary.atlassian.net/browse/APPS-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-2802]: https://uclalibrary.atlassian.net/browse/APPS-2802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2780, APPS-2781,  APPS-2802 and update component library version due to switching branches

- .github/workflows/auto-build.yml
- .github/workflows/ci.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
- .github/workflows/percy.yml
- package.json
- pnpm-lock.yaml
Connected to [APPS-2849](https://jira.library.ucla.edu/browse/APPS-2849)
[APPS-2849]: https://uclalibrary.atlassian.net/browse/APPS-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: Update build timings and nuxt config build options to reduce the load on craft server

- .github/workflows/auto-build.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
Connected to [APPS-2860](https://jira.library.ucla.edu/browse/APPS-2860)
[APPS-2860]: https://uclalibrary.atlassian.net/browse/APPS-2860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ci update timeout to 50 minutes

- .github/workflows/auto-build.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
- nuxt.config.js
Connected to [APPS-2860](https://jira.library.ucla.edu/browse/APPS-2860)
[APPS-2860]: https://uclalibrary.atlassian.net/browse/APPS-2860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove timeout update conurrency from 10 to 50

- .github/workflows/auto-build.yml
- .github/workflows/on-release.yml
Connected to [APPS-2811](https://jira.library.ucla.edu/browse/APPS-2811)
[APPS-2811]: https://uclalibrary.atlassian.net/browse/APPS-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: replace npm with pnpm

- .github/workflows/auto-build.yml
- .github/workflows/ci.yml
- .github/workflows/on-release.yml
- pages/about/programs/[slug].vue
Connected to [APPS-2904](https://jira.library.ucla.edu/browse/APPS-2904)
Connected to [APPS-2909](https://jira.library.ucla.edu/browse/APPS-2909)
[APPS-2904]: https://uclalibrary.atlassian.net/browse/APPS-2904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-2909]: https://uclalibrary.atlassian.net/browse/APPS-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Unprocessable Entity error in GH action and issue with programs preview

- app.vue
- layouts/default.vue
Connected to [APPS-2979](https://jira.library.ucla.edu/browse/APPS-2979)
[APPS-2979]: https://uclalibrary.atlassian.net/browse/APPS-2979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add lib cost study survey in production

- app.vue
- nuxt.config.ts
- package.json
- pnpm-lock.yaml
Connected to [APPS-2987](https://jira.library.ucla.edu/browse/APPS-2987)
[APPS-2987]: https://uclalibrary.atlassian.net/browse/APPS-2987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: draft preview header data fixed

- package.json
- pages/index.vue
- pnpm-lock.yaml
Connected to [APPS-2922](https://jira.library.ucla.edu/browse/APPS-2922)
**Notes:**
Updating the package to pull in latest component changes to CardMeta & BlockCardWithImage from this PR: https://github.com/UCLALibrary/ucla-library-website-components/pull/637
In order to fix the time on the homepage, we need to update the component library. This PR will do that. 
**Checklist:**
-   [X] I added github label for semantic versioning
-   [X] I double checked it looks like the designs
-   ~~[ ] I completed any required mobile breakpoint styling~~
-   ~~[ ] I completed any required hover state styling~~
-   ~~[ ] I included a working spec file~~
-   [X] I added notes above about how long it took to build this component
-   ~~[ ] UX has reviewed this PR~~
-   [ ] I assigned this …
> fix: time on homepage

- nuxt.config.ts
- package.json
- pages/search-site/index.vue
- plugins/update-library-alert.client.js
- pnpm-lock.yaml
Connected to [APPS-3012](https://jira.library.ucla.edu/browse/APPS-3012)
https://deploy-preview-866--uclalibrary-test.netlify.app/impact/
Connected to [APPS-3048](https://jira.library.ucla.edu/browse/APPS-3048)
External news article uri working in search results https://deploy-preview-866--uclalibrary-test.netlify.app/search-site?q=preview
[APPS-3012]: https://uclalibrary.atlassian.net/browse/APPS-3012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-3048]: https://uclalibrary.atlassian.net/browse/APPS-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update impact report story category and external news uri on site search results

- nuxt.config.ts
- pages/about/news/index.vue
- utils/searchConfig.js
Connected to [APPS-3048](https://jira.library.ucla.edu/browse/APPS-3048)
[APPS-3048]: https://uclalibrary.atlassian.net/browse/APPS-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: news listing search results external news url

- .github/workflows/ci.yml
- .github/workflows/setup-workspace/action.yml
- pages/about/news/index.vue
- pages/impact/[year]/[slug].vue
Connected to [APPS-3083](https://jira.library.ucla.edu/browse/APPS-3083)
[APPS-3083]: https://uclalibrary.atlassian.net/browse/APPS-3083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: set padding top and bottom for sectionwrapper rich text content

- public/_redirects
Connected to [APPS-3126](https://jira.library.ucla.edu/browse/APPS-3126)
[APPS-3126]: https://uclalibrary.atlassian.net/browse/APPS-3126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add redirect

- public/_redirects
Connected to [APPS-3143 ](https://jira.library.ucla.edu/browse/APPS-3143 )
https://deploy-preview-872--uclalibrary-test.netlify.app/special-collections/discover-collections/online-exhibits/bloodletting-exhibit
---
redirect this link:
https://www.library.ucla.edu/special-collections/discover-collections/online-exhibits/bloodletting-exhibit 
to:
https://guides.library.ucla.edu/c.php?g=390460&p=10130567#s-lg-box-wrapper-39819540
> feat: APPS-3143 website URL redirect

- pages/help/services-resources/index.vue
Connected to [APPS-2447](https://jira.library.ucla.edu/browse/APPS-2447)
**Page/Pages Created/updated:** pages/help/services-resources/index..vue 
**Notes:**
After combining these categories the category name/label for External Resource is also Resource
This took me 10 minutes.
[APPS-2447]: https://uclalibrary.atlassian.net/browse/APPS-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update external resource to be resource to combine resource and  external resource as one category

- composables/useSearch.ts
- modules/init.js
- utils/searchConfig.js
Connected to [APPS-3251](https://jira.library.ucla.edu/browse/APPS-3251)
Add char_filter and edge_ngram_tokenizer
searching hoff https://deploy-preview-878--uclalibrary-test.netlify.app/search-site/?q=hoff&filters=
searching jen https://deploy-preview-878--uclalibrary-test.netlify.app/search-site/?q=jen&filters=
We don't have good example for more partial searches and words with hypens in the test data, But I tested it in production
[APPS-3251]: https://uclalibrary.atlassian.net/browse/APPS-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3251

- .github/workflows/ci.yml
- composables/useSearch.ts
- modules/init.js
- package.json
- pages/search-site/index.vue
- pnpm-lock.yaml
Connected to [APPS-1976](https://jira.library.ucla.edu/browse/APPS-1976)
**Notes:**
New component for Search in Navigation added to component library, us this new version in this repo
[APPS-1976]: https://uclalibrary.atlassian.net/browse/APPS-1976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add search to Nav

- composables/useSearch.ts
- pages/search-site/index.vue
Connected to [APPS-3489](https://jira.library.ucla.edu/browse/APPS-3489)
[APPS-3489]: https://uclalibrary.atlassian.net/browse/APPS-3489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: show only 10 records if search term is misspelt
