- .github/workflows/ci.yml
- .github/workflows/setup-workspace/action.yml
- .npmrc
- components/BlockLocationListItem.vue
- components/HeaderMainResponsive.vue
- components/MediaGallery/ThumbnailCard.vue
- components/SearchGeneric.vue
- layouts/default.vue
- package-lock.json
- package.json
- stories/BlockLocationListItem.stories.js
- stories/HeaderMainResponsive.stories.js
Connected to [APPS-1570](https://jira.library.ucla.edu/browse/APPS-1570)
This PR will:
- Update node and npm
- Remove component imports from storybook
- Remove components: true
- Adds formatting
All devs should download node16.15.0, I prefer nvm, that way we can switch between node versions if needed based on project.
- Delete package-lock.json
- Delete node_modules/
- Run npm install
- Make sure package-lock.json does not change.
> chore!: Upgrade node to 16.15.0

- components/BlockCampusMap.vue
- components/Flexible/MediaWithText.vue
- components/SectionSpacesList.vue
- components/SectionTeaserCard.vue
- gql/queries/LocationDetail.gql
- gql/queries/ServiceOrResourceDetail.gql
- pages/visit/locations/_slug.vue
Connected to [APPS-1572](https://jira.library.ucla.edu/browse/APPS-1572) and [APPS-1573](https://jira.library.ucla.edu/browse/APPS-1573)
[APPS-1572](https://jira.library.ucla.edu/browse/APPS-1572)
- Remove Spaces title from page template locations/_slug.vue
- Hard code "Spaces" as title of BlockSpaces component (no longer including library location name, matching BlockHours and BlockCampusMap)
- Remove location link
[APPS-1573](https://jira.library.ucla.edu/browse/APPS-1573)
- Fix graphql for Craft updates
> fix: update graphql queries and location detail page

- .github/configs/release-drafter.yml
Going forward, Before we merge the PR's we need to add following Github labels:
- breaking - A change that breaks backwards compatibility (this represents a major version bump)
A change that fixes something in a backwards compatible way (this represents a patch version bump)
- bugfix 
- fix
- chore
- documentation
- ci
An improvement to an existing feature (this represents a minor version bump)
- enhancement
- feature
- refactor
> chore: Add Github labels that release-drafter will use to decode the version number

- .github/workflows/ci.yml
Right now we have following
and this PR will add `test` to the list.
> ci: On merge to main github-deployment-environment is set to test

- components/BannerFeatured.vue
- components/BannerHeader.vue
- components/BannerText.vue
- components/BlockCampusMap.vue
- components/BlockSpaces.vue
- pages/about/news/_slug.vue
- pages/visit/locations/_slug.vue
Connected to [APPS-1653](https://jira.library.ucla.edu/browse/APPS-1653)
Using the Library
Remove block-campus-map and divider-general
Services & Resources
Flexible Page Blocks
Events & Exhibitions
(remove Endowments)
About
Location & Access 
> fix: APPS-1653 Update Location template

- .github/workflows/on-publish.yml
This PR  fixes the issue when deploying to production Nuxt use the production craft endpoint. Will add the cypress test job to GH action later when @sourcefilter is back.
> ci: Remove cypress test from production deploy and update craft end point to production

- layouts/error.vue
- copy and paste error layout used on meap site
- discovered an issue that the error pages do not render. getting the general content page template instead ([APPS-1953](https://jira.library.ucla.edu/browse/APPS-1953))
> feat: adds same error page layout used on meap site

- package-lock.json
- package.json
- pages/impact/_year/_slug.vue
- pages/impact/_year/index.vue
Connected to [APPS-1997](https://jira.library.ucla.edu/browse/APPS-1997)
- Update to ucla-library-components to use new banners that internally determine image vs video
> fix: update banners on impact pages

- pages/impact/_year/index.vue
Adds object-fit: cover property to Ginny's image on Impact Report header
**Checklist:**
-   [x] UX has reviewed this PR
> fix: resolve ginny-portrait aspect ratio

- pages/impact/_year/_slug.vue
- pages/impact/_year/index.vue
- hides the gradient, molecule, and hatch from the section-banner
> fix: remove all overlays from impact banners

- pages/impact/_year/index.vue
- adds space between Ginny's letter and image on desktop display to avoid text running into portrait
**Checklist:**
> feat: adds space between ginny's letter and image

- pages/about/programs/_slug.vue
BannerHeader and BannerText
View Staff Directory link only appears on Program entries with "Yes" radio button selected; does not appear when "No" is selected
http://192.168.1.119:3000/about/programs/campus-library-instructional-computing-commons-clicc
https://deploy-preview-539--uclalibrary-test.netlify.app/about/programs/sinai/
> fix: staff-directory-link

- gql/fragments/BlockMediaGalleryExtraFieldsFragment.gql
- gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql
- pages/collections/_slug.vue
Connected to [APPS-2078](https://jira.library.ucla.edu/browse/APPS-2078)
Updates graphql to query correct content for collections media gallery FPB 
Broken on prod: https://uclalibrary.library.ucla.edu/collections/neutra-richard-and-dion-papers/?preview=true
Fixed when pointed at prod locally ![Screen Shot 2022-11-22 at 3 54 06 PM](https://user-images.githubusercontent.com/34147754/203444412-d46910e3-df70-474a-aa68-86b5e8cbf3dd.png)
> fix: mediagallery gql fix for collections detail page

- plugins/scrape-formid.client.js
Connected to [APPS-2107](https://jira.library.ucla.edu/browse/APPS-2107)
This fix will override the browser CORS issue with fetching formid from libcal for the event registration,
Services Team is looking into why the register api is not working anymore.
> fix: Use libcal proxy to avoid CORS issue

- .github/workflows/ci.yml
- gql/queries/GeneralContentDetail.gql
- pages/_.vue
- plugins/elasticsearchplugin.js
- fixes an issue where a final '/' (often inserted by nuxt automatically) would cause a 404
- fixes a potential issue with slug collisions of nested pages (e.g. if we had pages '/abc/def' and '/ghi/def')
> fix: find general content pages by full uri path

- nuxt.config.js
Fixes a fairly obscure issue where the viewport width (used to determine which header to show) was incorrect when the responsive window size was set to 1024px or smaller in Chrome devtools.
I was unable to reproduce the issue elsewhere and don't understand the full implications of this change, so I don't know if it's worth making. But as far as I can tell everything looks good.
> fix: window.innerWidth in Chrome devtools

- gql/queries/EventDetail.gql
- gql/queries/ExhibitionsAndEventsList.gql
- gql/queries/JobOpportunitiesList.gql
- gql/queries/JobStudentOpportunitiesList.gql
- gql/queries/JobsList.gql
- gql/queries/LocationDetail.gql
- pages/about/jobs/staff-academic-jobs/index.vue
- pages/about/programs/index.vue
- pages/about/student-opportunities/index.vue
- pages/help/services-resources/_slug.vue
- pages/visit/events-exhibitions/_slug.vue
- pages/visit/locations/_slug.vue
Connected to [UX-527](https://jira.library.ucla.edu/browse/UX-527)
- on location detail, updates event sort order to be ascending with exhibitions (typically ongoing) listed first
- adds "ongoing" to exhibition, event series, and workshop series queries
- on program listing, updates featured display to work when only one featured program is selected
- on event and workshop series, fixes divider display for associated events
- on staff-academic-job listing, fixes associated topics link
> feat: update location detail

- assets/styles/global.scss
- package-lock.json
- package.json
- pages/about/news/index.vue
- pages/about/programs/index.vue
- pages/about/staff/index.vue
- pages/collections/access/index.vue
- pages/collections/explore/index.vue
- pages/give/endowments/index.vue
- pages/help/_slug.vue
- pages/help/services-resources/index.vue
- pages/index.vue
- pages/search-site/index.vue
- pages/visit/events-exhibitions/index.vue
- pages/visit/locations/index.vue
Connected to [UX-927](https://jira.library.ucla.edu/browse/UX-927)
- standardizes index page spacing and dividers for search/filters (except for Services-Resources and Staff WIP)
- updates to use h2 for about-results text
- updates component library
> feat: standardize search filter spacing

- package-lock.json
- package.json
- pages/about/programs/_slug.vue
- pages/collections/index.vue
- pages/index.vue
- pages/visit/locations/_slug.vue
Connected to [APPS-2159](https://jira.library.ucla.edu/browse/APPS-2159) & Connected to [APPS-2124](https://jira.library.ucla.edu/browse/APPS-2124)
Updates Component Library to  "version": "2.35.3",
+ On Location detail: "View staff directory" link in banner --> Staff Directory listing filtered by relevant location
+ https://deploy-preview-658--uclalibrary-test.netlify.app/visit/locations/biomed/
+ https://deploy-preview-658--uclalibrary-test.netlify.app/visit/locations/data-science-center/
+ On Program detail: "View staff directory link in banner" --> Staff Directory listing filtered by relevant department (CLICC, DLP)
+ https://deploy-preview-660--uclalibrary-test.netlify.app/about/programs/digital-library-program/
+ https://deploy-preview-660--uclalibrary-test.netlify.app/about/programs …
> feat: APPS-2159 feat: Replace links with filtered search views

- .github/workflows/on-release.yml
Have to use a personal access token for one workflow to trigger another – see https://github.com/orgs/community/discussions/27028
> fix: trigger auto-build.yml from on-release.yml

- layouts/default.vue
- layouts/error.vue
Homepage is "UCLA Library": https://deploy-preview-688--uclalibrary-test.netlify.app/ 
Error is "Error | UCLA Library": https://deploy-preview-688--uclalibrary-test.netlify.app/safoeifj
Other pages are "{{page.title}} | UCLA Library": https://deploy-preview-688--uclalibrary-test.netlify.app/help/services-resources/borrowing-books-and-equipment
> fix: update page title for homepage and error templates

- gql/queries/CollectionDetail.gql
- pages/about/staff/index.vue
- pages/collections/explore/_slug.vue
Connected to [APPS-2282](https://jira.library.ucla.edu/browse/APPS-2282)
Connected to [WST-126](https://jira.library.ucla.edu/browse/WST-126)
- adds missing staff contact info to collection detail page
- fixes alt language name display on staff directory
> fix: staff contact and alt language display

- package-lock.json
- package.json
- pages/about/staff/index.vue
Connected to [WST-126](https://jira.library.ucla.edu/browse/WST-126)
- Removes altName from staffName in parseHits. Staff name should now appear correct on staff directory index from page load and search results load
> fix: remove altName from staffName in parseHits

- cypress/e2e/eventsexhibitionslist.cy.js
- utils/flattenTimeLineStructure.js
fix broken impact report in production due to missing hero image on an article used on the impact report
> fix: check length of heroimage array, getting empty array from craft

- cypress.config.js
- gql/queries/CollectionDetail.gql
- gql/queries/StaffList.gql
- pages/about/staff/index.vue
- pages/collections/explore/_slug.vue
- pages/give/endowments/index.vue
- utils/fixUri.js
[APPS-2333](https://jira.library.ucla.edu/browse/APPS-2333) - FIX: Library Location links go to 404 pages on Block Staff List in Staff Directory and Collection Detail pages
[APPS-2334](https://jira.library.ucla.edu/browse/APPS-2334) - FIX: Library Location links go to 404 pages in filtered view of Endowments and Jobs Listing page
> fix: location links in various pages

- package-lock.json
- package.json
- pages/give/endowments/index.vue
Connected to [APPS-2300](https://jira.library.ucla.edu/browse/APPS-2300)
commented out donor filter https://deploy-preview-714--uclalibrary-test.netlify.app/give/endowments/
> fix: APPS-2300_remove-donor-filter

- pages/about/news/_slug.vue
Connected to [APPS-2385](https://jira.library.ucla.edu/browse/APPS-2385)
**Two Staff Members:**
https://deploy-preview-721--uclalibrary-test.netlify.app/about/news/shortbread-featured-promo
**Two Ex- Staff Members**
https://deploy-preview-721--uclalibrary-test.netlify.app/about/news/testnews
**External Author & Staff Member**
https://deploy-preview-721--uclalibrary-test.netlify.app/about/news/casper-the-ghost/
**Ex- Staff Member & External Author**
https://deploy-preview-721--uclalibrary-test.netlify.app/about/news/test-news-title-test-for-bannertext
**Two External Authors**
https://deploy-preview-721--uclalibrary-test.netlify.app/about/news/la-ni%C3%B1a
**Ex- Staff Member & External Author**
https://deploy-preview-721--uclalibrary-test.netlify.app/about/news/test-news-title-test-for-banne …
> fix: APPS-2385 byline error on production news article

- pages/about/programs/index.vue
Connected to [APPS-2403](https://jira.library.ucla.edu/browse/APPS-2403)
> fix: APPS-2403 buttonurl is not required if the program URL behaviour is external

- pages/impact/all.vue
because this page gets internal links in production, nuxt was building a page for it, which netlify served instead referring to _redirects
> fix: vue redirect for /impact/all

- package-lock.json
- package.json
- pages/search-site/index.vue
Connected to [APPS-2422](https://jira.library.ucla.edu/browse/APPS-2422)
On the Library Website Search, the results list a content type label at the top of every result. The one labelled “LIBGUIDE” needs to be changed to “RESEARCH GUIDE”
[APPS-2422]: https://uclalibrary.atlassian.net/browse/APPS-2422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2422 Change "LIBGUIDE" label on Search Results to "RESEARCH GUIDE"

- package-lock.json
- package.json
Connected to [APPS-2055](https://jira.library.ucla.edu/browse/APPS-2055)
[APPS-2055]: https://uclalibrary.atlassian.net/browse/APPS-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: APPS-2055 Update component library to update richText media embed to include half and full width options

- static/blockCliccHours.html
- static/blockHours.html
Connected to [APPS-2536](https://jira.library.ucla.edu/browse/APPS-2536)
---
Add `.s-lc-byap` & `.s-lc-timetxt` To fix 2. & 3. At line 144
```
.s-lc-time,
.s-lc-allday,
.s-lc-closed,
.s-lc-byap,
.s-lc-timetxt,
.s-lc-whw-locname,
.s-lc-whw-sublocname {
font-family: 'proxima-nova';
font-size: 16px;
}
```
From: (too big)
To:
---
From: (too big)
To:
[APPS-2536]: https://uclalibrary.atlassian.net/browse/APPS-2536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style: APPS-2536 LibCal/Hours website widget formatting

- .github/workflows/ci.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
- .github/workflows/percy.yml
- layouts/default.vue
- modules/swapAliasIndexGenerator.js
- nuxt.config.js
- plugins/update-library-site-alert.client.js
- store/index.js
Connected to [APPS-2540](https://jira.library.ucla.edu/browse/APPS-2540)
Connected to [APPS-2579](https://jira.library.ucla.edu/browse/APPS-2579)
Notes:
This PR creates temp libguides index for the build and replaces the indes created by systems team with new one in the alias
and also we have anew client side plugin which will call store action to update global data like site alert on client side. So we dont have to rebuild the site to see the site alert changes.
[APPS-2540]: https://uclalibrary.atlassian.net/browse/APPS-2540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-2579]: https://uclalibrary.atlassian.net/browse/APPS-2579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: create libguides temp index and update site alert on the clientside

- .github/workflows/setup-workspace/action.yml
This PR may fix:
Following error:
/usr/local/bin/npx cypress cache list
No cached binary versions were found.
/usr/local/bin/npx cypress verify
The cypress npm package is installed, but the Cypress binary is missing.
We expected the binary to be installed here: /home/runner/.cache/Cypress/12.17.4/Cypress/Cypress
Reasons it may be missing:
- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress
Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
Alternatively, you can run 'cypress install' to download the binary again.
https://on.cypress.io/not-installed-ci-error
----------
Platform: linux-x64 (Ubuntu - 22.04)
Cypress …
> ci: fix cypress binary error

- nuxt.config.ts
- pages/about/news/index.vue
- pages/impact/[year]/index.vue
Connected to [APPS-2614](https://jira.library.ucla.edu/browse/APPS-2614)
Fixes following build warnings and errors in the browser console
_~ucla-library-design-tokens/assets/fonts/karbon-web-light.woff2 referenced in /Users/parinitamulak/library-website-nuxt/node_modules/.pnpm/ucla-library-design-tokens@5.8.0/node_modules/ucla-library-design-tokens/scss/app-global.scss?inline&used didn't resolve at build time, it will remain unchanged to be resolved at runtime_
[APPS-2614]: https://uclalibrary.atlassian.net/browse/APPS-2614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: font errors

- package-lock.json
- package.json
Connected to [PR-486](https://github.com/UCLALibrary/ucla-library-website-components/pull/486)
Courtney reported a bug earlier today. The salary ranges are not showing if the department value is empty.
[PR-486]: https://uclalibrary.atlassian.net/browse/PR-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: fix salary ranges / update ucla-library-website-components

- gql/fragments/BlockImpactNumberCardsFragment.gql
Connected to [APPS-2664](https://jira.library.ucla.edu/browse/APPS-2664)
**Page/Pages Created/updated:** gql/fragments/BlockImpactNumberCardsFragment.gql from #APPS-2664
**Notes:**
Removed an extra query from BlockImpactNumberCardsFragment.gql 
This took me 45ish minutes to edit and test.
**Checklist:**
-   [ X] I added notes above about how long it took to build this component
[APPS-2664]: …
> fix: APPS-2664 Remove query portion that is not required

- .github/workflows/auto-build.yml
- .github/workflows/ci.yml
- .github/workflows/manual-site-build.yml
- .github/workflows/on-release.yml
- .github/workflows/percy.yml
- cypress/e2e/collectionsaccesspage.cy.js
- cypress/e2e/eventsexhibitionslist.cy.js
- cypress/e2e/sitesearch.cy.js
- modules/init.js
- nuxt.config.ts
- package.json
- pages/search-site/index.vue
- pages/visit/locations/[slug].vue
- plugins/indexer.server.js
- pnpm-lock.yaml
- server/api/fetchTempIndexName.js
Connected to [APPS-2662](https://jira.library.ucla.edu/browse/APPS-2662)
**Page/Pages Created/updated:** /search-site/index.vue 
**Notes:**
There is a bug in the search-home component, https://uclalibrary.atlassian.net/browse/APPS-2668, which will be fixed first before we merge this.
This took me 2 hours to build this. But I had to fix an `insert before` error on the static page and I also found out that tests were failing as useStorage which was storing the temp index was not reliable. So I simplified it to create the temp index name in Nuxt config, removed it from init.js, and cleaned up some unwanted code
**Checklist:**
-   [ ] I completed any required mobile …
> feat: APPS-2662 Migrate search-site template 

- cypress/e2e/collectionsexplorepage.cy.js
- gql/fragments/BlockAssociatedTopicCardsFragment.gql
- pages/about/news/index.vue
- pages/collections/access/index.vue
- pages/collections/explore/index.vue
- pages/help/services-resources/index.vue
Connected to [APPS-2658](https://jira.library.ucla.edu/browse/APPS-258)
Connected to [APPS-2657](https://jira.library.ucla.edu/browse/APPS-2657)
Connected to [APPS-2670](https://uclalibrary.atlassian.net/browse/APPS-2670)
1. APPS-2658 Migrate collections/explore index page template to nuxt3 branch
2. APPS-2657 Enable Elastic Search on the Collections Explore Listing page
3. APPS-2670 Associated Topics FPB is not pulling in correct illustration for Card with Illustration component - external record
**Page converted to Nuxt3 ** collections/explore/index.vue
**Notes:**
1. I updated the query `BlockAssociatedTopicCardsFragment.gql` to include: iconName: `illustrationsResourcesAndServices` to fix the Article page FPB Associated Topics Illustrations for External Resources
2. …
> feat: APPS-2658   Migrate collections/explore index page template to nuxt3

- app.vue
- nuxt.config.ts
- pages/collections/explore/index.vue
Connected to [APPS-2716](https://jira.library.ucla.edu/browse/APPS-2716)
- Added configuration for [page transitions](https://nuxt.com/docs/getting-started/transitions#global-settings) and progress bar loading
- In Nuxt3, settings for progress bar loading are now enabled via the `<NuxtLoadingIndicator>` component, which is added to `app.vue`
- Reference: [Nuxt2 documentation](https://v2.nuxt.com/docs/configuration-glossary/configuration-loading/), [Nuxt3 documentation](https://nuxt.com/docs/api/components/nuxt-loading-indicator)
**Checklist:**
-   [x] I added notes
[APPS-2716]: https://uclalibrary.atlassian.net/browse/APPS-2716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> chore: APPS-2716 Update Nuxt3 config

- cypress/e2e/articlenewslistingpage.cy.js
- cypress/e2e/collectionsexplorepage.cy.js
- cypress/e2e/eventsexhibitionslist.cy.js
- cypress/e2e/policiesdetailpage.cy.js
Connected to [APPS-2682](https://jira.library.ucla.edu/browse/APPS-2682)
**Notes:**
Adding a bit more resilience to specific flaky page tests
**Checklist:**
-   [ ] I added github label for semantic versioning
[APPS-2682]: https://uclalibrary.atlassian.net/browse/APPS-2682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2682 intercept and wait on flaky tests

- app.vue
- layouts/default.vue
- package.json
- pnpm-lock.yaml
Connected to [APPS-2711](https://jira.library.ucla.edu/browse/APPS-2711)
**Preview:** https://deploy-preview-819--uclalibrary-test-nuxt3x.netlify.app/
**Notes:**
Re-enable Vue-Skip-To package after resolving underlying issue with SearchInput component
- See related PR: [Fix tab focus in-out of search input field](https://github.com/UCLALibrary/ucla-library-website-components/pull/514/)
**Checklist:**
-   [x] I added notes
[APPS-2711]: https://uclalibrary.atlassian.net/browse/APPS-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2711 Fix Vue-Skip-To in Nuxt3

- gql/fragments/collections/ImpactReportFpb.gql
Connected to [APPS-2994](https://jira.library.ucla.edu/browse/APPS-2994)
**Query updated:** gql/fragments/collections/ImpactReportFpb.gql.vue
**Notes:**
Recently in Craft we updated ImpactReportFBP with new block -> Rich Text, to support this on the nuxt side, we need to update the GQL query
This took me 5 mins to work on this.
[APPS-2994]: https://uclalibrary.atlassian.net/browse/APPS-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add rich text fragment to impact report FBP query

- public/_redirects
Connected to [APPS-3131](https://jira.library.ucla.edu/browse/APPS-3131)
Remove any reference to https://library.ucla.edu/* redirect source paths. 
Checked if all the 3 HAProxy URL redirects are in the redirects file in this app.
[APPS-3131]: https://uclalibrary.atlassian.net/browse/APPS-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove library.ucla.edu/givemusic and remove a trailing slash

- composables/useSearch.ts
- package.json
- pages/about/news/index.vue
- pages/about/programs/index.vue
- pages/about/staff/index.vue
- pages/collections/access/index.vue
- pages/collections/explore/index.vue
- pages/give/endowments/index.vue
- pages/help/services-resources/index.vue
- pages/search-site/index.vue
- pages/visit/events-exhibitions/index.vue
- pages/visit/locations/index.vue
- pnpm-lock.yaml
- utils/formatDates.js
- utils/formatTimes.js
- utils/searchConfig.js
**JIRA:** [APPS-2576](https://jira.library.ucla.edu/browse/APPS-2576) and [APPS-3252](https://uclalibrary.atlassian.net/browse/APPS-3252)
This PR improves the accuracy, relevance, and flexibility of our Elasticsearch keyword search.
---
- Enabled typo tolerance using `fuzziness: AUTO` (e.g., `telivision` → `television`)
- Switched from `query_string` fuzziness to a layered `bool` query:
- `must`: exact match (`multi_match`)
- `should`: fuzzy match + `match_phrase` for boosting
- `filter`: scoped filtering (e.g., `sectionHandle`, `displayEntry`)
- Fixed issue where sorting by `title.keyword` caused `_score` to be `null`
- Now sorting by relevance (`_score`) first, then alphabetically
---
- Avoids noisy fuzzy results like `"cheese"` when searching for `"chinese"`
- Ensures typo tolerance …
> feat: Search Improvements APPS-2576
